version: "3"

volumes:
  db-data:

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/${DB_NAME}/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  nginx:
    image: nginx:stable-alpine
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/app # Mount source code folder in host machine to the container
      - ./.env:/usr/src/app/.env
    command: npm run start:dev
    ports:
      - "3000:3000"