version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - APP_ENV=${APP_ENV} # Pass APP_ENV arg to Dockerfile
    volumes:
      - ./frontend/app:/usr/src/app/app # Mount src folder in host machine to the container
      - ./frontend/config:/usr/src/app/config
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
      - ./.env:/usr/src/app/.env.local
    command: [sh, -c, "npm run start:${APP_ENV}"]
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV} # Pass APP_ENV arg to Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/src # Mount src folder in host machine to the container
      - ./backend/package.json:/usr/src/app/package.json
      - .env:/usr/src/.env
    command: [sh, -c, "npm run migrate:${APP_ENV} && npm run start:${APP_ENV}"]
    ports:
      - "8080:8080"
  database:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/${DB_NAME}/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  proxy:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    
volumes: # Create user defined volumn for sharing data among multiple services
  app-data: 

# networks: # Create user defined network for comunicating among multiple services
#   app-network: